### ISSUE TITLE
Generator using fuel while not in use.

### ISSUE THREAD

**Issue by Bullorg74** [Zaexides/SteamWorld#16]
# Issue Report

Question

Misc: Should the steam generator continue burning coal even when nothing is conncected that uses steam? It does for me. I remember it stopping in earlier version. (might remember wrong)

### Suggestion

I think it should not burn fuel when steam is not beeing used.

Steam world 1.12.2-0.3.0.4.a
Forge 14.23.3.2668

**Comment by Zaexides** [comment]
Nope! Once the fuel is burning, it will keep doing so until it runs out. After that, it should only start burning the next fuel if there's both water in the water tank and empty space in the steam tank, not unlike how vanilla Furnaces work with cooking/smelting items and blocks.

**Comment by Bullorg74** [comment]
Ok it cleared a stack of coal blocks with only water in conected.

And testing now it burnt 6 coal with nothing connected and not using water and all my tests are with full water and steam tanks.

**Comment by Zaexides** [comment]
I'll have to look into that then.

**Comment by Zaexides** [comment]
Alright, this issue seemed to have come from slight mod incompatibility with another mod (I'd assume Mekanism), since the steam generator as of now checks if its output tank is filled with SteamWorld steam, whereas Mekanism overrides it with its own steam.
This issue should be fixed in the next update (0.3.1.0) so keep an eye out for that, and thank you very much for bringing this to my attention! :)
